name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip mnbp directory
        run: |
          cd custom_components/mnbp
          zip -r mnbp.zip ./
          mv mnbp.zip ${{ github.workspace }}

      - name: Create GitHub release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          files: mnbp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
